name: visionnerf
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
      - opencv-python
      - imageio
      - imageio-ffmpeg
      - ipdb
      - timm
      - configargparse
      - einops
      - tensorboardX
  - scipy
  - numpy
  - matplotlib
  - pytorch==1.10.0
  - torchvision==0.11.1
  - tqdm
  - cudatoolkit==11.3.1